{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Pizza", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " Revenue/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_revenue_usd_total[$__rate_interval]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation failures/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_pizza_creation_failures_total[$__rate_interval]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas sold/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_pizzas_sold_total[$__rate_interval]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "jwt_pizza_service_pizza_creation_latency_ms_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service endpoint latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg by (http_route) (jwt_pizza_service_http_request_latency_ms_milliseconds{http_route!=\"/favicon.ico\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage percentage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jwt_pizza_service_cpu_usage_percent",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage percentage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jwt_pizza_service_memory_usage_percent",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTTP 4xx/5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (http_response_status_class) (rate(jwt_pizza_service_http_responses_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " HTTP requests/minute by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (http_request_method) (rate(jwt_pizza_service_http_requests_total[$__rate_interval])) * 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jwt_pizza_service_http_requests_total)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth and Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jwt_pizza_service_active_users_ratio",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Authentication attempts/minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum by (result) (rate(jwt_pizza_service_auth_attempts_total[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}